# Generated by Django 6.0 on 2025-12-23 16:39

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Bom',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('quantity', models.DecimalField(decimal_places=6, max_digits=18)),
            ],
            options={
                'db_table': 'bom',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='BusinessEntity',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.TextField()),
                ('display_name', models.TextField()),
            ],
            options={
                'db_table': 'business_entity',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='Class',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.TextField()),
                ('display_name', models.TextField()),
            ],
            options={
                'db_table': 'class',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='ClassParameter',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('min_value', models.FloatField(blank=True, null=True)),
                ('max_value', models.FloatField(blank=True, null=True)),
                ('is_required', models.BooleanField()),
            ],
            options={
                'db_table': 'class_parameter',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='ConfigRule',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.TextField()),
                ('description', models.TextField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'db_table': 'config_rule',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='Enum',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.TextField()),
                ('display_name', models.TextField()),
            ],
            options={
                'db_table': 'enum',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='EnumValue',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.TextField()),
                ('display_name', models.TextField()),
                ('value_int', models.IntegerField(blank=True, null=True)),
                ('value_real', models.FloatField(blank=True, null=True)),
                ('value_str', models.TextField(blank=True, null=True)),
            ],
            options={
                'db_table': 'enum_value',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='InputResource',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('in_quantity', models.DecimalField(decimal_places=6, max_digits=18)),
                ('out_quantity', models.DecimalField(decimal_places=6, max_digits=18)),
            ],
            options={
                'db_table': 'input_resource',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='Measure',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.TextField(unique=True)),
                ('name_short', models.TextField(unique=True)),
            ],
            options={
                'db_table': 'measure',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='OrderPos',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('quantity', models.DecimalField(decimal_places=6, max_digits=18)),
            ],
            options={
                'db_table': 'order_pos',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='Orders',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField()),
                ('status', models.TextField()),
            ],
            options={
                'db_table': 'orders',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='Parameter',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.TextField()),
                ('display_name', models.TextField()),
            ],
            options={
                'db_table': 'parameter',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='ProductParameter',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('value_int', models.IntegerField(blank=True, null=True)),
                ('value_real', models.FloatField(blank=True, null=True)),
                ('value_str', models.TextField(blank=True, null=True)),
            ],
            options={
                'db_table': 'product_parameter',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='Products',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('code', models.TextField(unique=True)),
                ('name', models.TextField()),
            ],
            options={
                'db_table': 'products',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='RuleCondition',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('order', models.IntegerField(blank=True, null=True)),
                ('logic_op', models.TextField(blank=True, null=True)),
            ],
            options={
                'db_table': 'rule_condition',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='RulePredicate',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('value_int', models.IntegerField(blank=True, null=True)),
                ('value_real', models.FloatField(blank=True, null=True)),
                ('value_str', models.TextField(blank=True, null=True)),
                ('operator', models.TextField()),
            ],
            options={
                'db_table': 'rule_predicate',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='TechOp',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('pos', models.IntegerField()),
                ('op_class', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, related_name='techop_op_class_set', to='db_admin.class')),
                ('product', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to='db_admin.products')),
            ],
        ),
    ]
