# Generated by Django 6.0 on 2025-12-23 16:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('db_admin', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Gwc',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.TextField()),
                ('display_name', models.TextField()),
            ],
            options={
                'db_table': 'gwc',
                'managed': False,
            },
        ),
        migrations.AlterModelOptions(
            name='techop',
            options={'managed': False},
        ),
    ]
