# Generated by Django 6.0 on 2025-12-23 16:58

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('db_admin', '0002_gwc_alter_techop_options'),
    ]

    operations = [
        migrations.AlterModelTable(
            name='techop',
            table='tech_op',
        ),
    ]
