# Generated by Django 6.0 on 2025-12-23 18:23

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('db_admin', '0003_alter_techop_table'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='bom',
            options={'managed': False, 'verbose_name': 'Состав изделия (BOM)', 'verbose_name_plural': 'Составы изделий (BOM)'},
        ),
        migrations.AlterModelOptions(
            name='businessentity',
            options={'managed': False, 'verbose_name': 'Бизнес-объект', 'verbose_name_plural': 'Бизнес-объекты'},
        ),
        migrations.AlterModelOptions(
            name='class',
            options={'managed': False, 'verbose_name': 'Класс', 'verbose_name_plural': 'Классы'},
        ),
        migrations.AlterModelOptions(
            name='classparameter',
            options={'managed': False, 'verbose_name': 'Параметр класса', 'verbose_name_plural': 'Параметры классов'},
        ),
        migrations.AlterModelOptions(
            name='configrule',
            options={'managed': False, 'verbose_name': 'Правило конфигурации', 'verbose_name_plural': 'Правила конфигурации'},
        ),
        migrations.AlterModelOptions(
            name='enum',
            options={'managed': False, 'verbose_name': 'Перечисление', 'verbose_name_plural': 'Перечисления'},
        ),
        migrations.AlterModelOptions(
            name='enumvalue',
            options={'managed': False, 'verbose_name': 'Значение перечисления', 'verbose_name_plural': 'Значения перечислений'},
        ),
        migrations.AlterModelOptions(
            name='gwc',
            options={'managed': False, 'verbose_name': 'Групповой рабочий центр', 'verbose_name_plural': 'Групповые рабочие центры'},
        ),
        migrations.AlterModelOptions(
            name='inputresource',
            options={'managed': False, 'verbose_name': 'Входной ресурс', 'verbose_name_plural': 'Входные ресурсы'},
        ),
        migrations.AlterModelOptions(
            name='measure',
            options={'managed': False, 'verbose_name': 'Единица измерения', 'verbose_name_plural': 'Единицы измерения'},
        ),
        migrations.AlterModelOptions(
            name='orderpos',
            options={'managed': False, 'verbose_name': 'Позиция заказа', 'verbose_name_plural': 'Позиции заказов'},
        ),
        migrations.AlterModelOptions(
            name='orders',
            options={'managed': False, 'verbose_name': 'Заказ', 'verbose_name_plural': 'Заказы'},
        ),
        migrations.AlterModelOptions(
            name='parameter',
            options={'managed': False, 'verbose_name': 'Параметр', 'verbose_name_plural': 'Параметры'},
        ),
        migrations.AlterModelOptions(
            name='productparameter',
            options={'managed': False, 'verbose_name': 'Значение параметра изделия', 'verbose_name_plural': 'Значения параметров изделий'},
        ),
        migrations.AlterModelOptions(
            name='products',
            options={'managed': False, 'verbose_name': 'Изделие', 'verbose_name_plural': 'Изделия'},
        ),
        migrations.AlterModelOptions(
            name='rulecondition',
            options={'managed': False, 'verbose_name': 'Условие в правиле', 'verbose_name_plural': 'Условия в правилах'},
        ),
        migrations.AlterModelOptions(
            name='rulepredicate',
            options={'managed': False, 'verbose_name': 'Условие правила', 'verbose_name_plural': 'Условия правил'},
        ),
        migrations.AlterModelOptions(
            name='techop',
            options={'managed': False, 'verbose_name': 'Технологическая операция', 'verbose_name_plural': 'Технологические операции'},
        ),
    ]
